-- CreateTable
CREATE TABLE `ShopBanner` (
    `id` VARCHAR(191) NOT NULL,
    `sectionLabel` VARCHAR(191) NULL DEFAULT 'HEALTH STORE',
    `title1` VARCHAR(191) NOT NULL,
    `highlightedText` VARCHAR(191) NULL,
    `title2` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `feature1Title` VARCHAR(191) NULL,
    `feature1Description` VARCHAR(191) NULL,
    `feature1Icon` VARCHAR(191) NULL,
    `feature2Title` VARCHAR(191) NULL,
    `feature2Description` VARCHAR(191) NULL,
    `feature2Icon` VARCHAR(191) NULL,
    `feature3Title` VARCHAR(191) NULL,
    `feature3Description` VARCHAR(191) NULL,
    `feature3Icon` VARCHAR(191) NULL,
    `feature4Title` VARCHAR(191) NULL,
    `feature4Description` VARCHAR(191) NULL,
    `feature4Icon` VARCHAR(191) NULL,
    `productSectionLabel` VARCHAR(191) NULL DEFAULT 'OUR SHOP',
    `productTitle1` VARCHAR(191) NULL,
    `productHighlightedText` VARCHAR(191) NULL,
    `productTitle2` VARCHAR(191) NULL,
    `productDescription` TEXT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
