-- CreateTable
CREATE TABLE `AboutSection` (
    `id` VARCHAR(191) NOT NULL,
    `sectionLabel` VARCHAR(191) NULL DEFAULT 'ABOUT US',
    `title1` VARCHAR(191) NOT NULL,
    `highlightedText` VARCHAR(191) NULL,
    `title2` VARCHAR(191) NULL,
    `description` VARCHAR(191) NOT NULL,
    `image` VARCHAR(191) NULL,
    `feature1Icon` VARCHAR(191) NULL,
    `feature1Title` VARCHAR(191) NULL,
    `feature1Description` VARCHAR(191) NULL,
    `feature2Icon` VARCHAR(191) NULL,
    `feature2Title` VARCHAR(191) NULL,
    `feature2Description` VARCHAR(191) NULL,
    `feature3Icon` VARCHAR(191) NULL,
    `feature3Title` VARCHAR(191) NULL,
    `feature3Description` VARCHAR(191) NULL,
    `patientsCount` VARCHAR(191) NULL,
    `doctorsCount` VARCHAR(191) NULL,
    `departmentsCount` VARCHAR(191) NULL,
    `experienceYears` VARCHAR(191) NULL,
    `patientsLabel` VARCHAR(191) NULL DEFAULT 'Happy Patients',
    `doctorsLabel` VARCHAR(191) NULL DEFAULT 'Expert Doctors',
    `departmentsLabel` VARCHAR(191) NULL DEFAULT 'Departments',
    `experienceLabel` VARCHAR(191) NULL DEFAULT 'Years Experience',
    `certificationTitle` VARCHAR(191) NULL,
    `certificationSubtitle` VARCHAR(191) NULL,
    `cardExperienceCount` VARCHAR(191) NULL,
    `cardExperienceLabel` VARCHAR(191) NULL DEFAULT 'Years',
    `cardPatientsCount` VARCHAR(191) NULL,
    `cardPatientsLabel` VARCHAR(191) NULL DEFAULT 'Patients',
    `primaryButtonText` VARCHAR(191) NULL,
    `secondaryButtonText` VARCHAR(191) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
