-- CreateTable
CREATE TABLE `AppointmentSection` (
    `id` VARCHAR(191) NOT NULL,
    `badgeText` VARCHAR(191) NULL DEFAULT 'NOW ACCEPTING PATIENTS',
    `title1` VARCHAR(191) NOT NULL,
    `highlightedText` VARCHAR(191) NULL,
    `title2` VARCHAR(191) NULL,
    `description` VARCHAR(191) NULL,
    `feature1Text` VARCHAR(191) NULL,
    `feature2Text` VARCHAR(191) NULL,
    `feature3Text` VARCHAR(191) NULL,
    `feature4Text` VARCHAR(191) NULL,
    `patientsServedCount` VARCHAR(191) NULL,
    `doctorsCount` VARCHAR(191) NULL,
    `ratingCount` VARCHAR(191) NULL,
    `patientsServedLabel` VARCHAR(191) NULL DEFAULT 'PATIENTS SERVED',
    `doctorsLabel` VARCHAR(191) NULL DEFAULT 'SPECIALIST DOCTORS',
    `ratingLabel` VARCHAR(191) NULL DEFAULT 'AVERAGE RATING',
    `phoneLabel` VARCHAR(191) NULL DEFAULT 'PREFER A CALL?',
    `phoneNumber` VARCHAR(191) NULL,
    `formTitle` VARCHAR(191) NULL,
    `formDescription` VARCHAR(191) NULL,
    `submitButtonText` VARCHAR(191) NULL,
    `sslText` VARCHAR(191) NULL,
    `confirmText` VARCHAR(191) NULL,
    `reviewText` VARCHAR(191) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
